version: "3.5"
services:

    # See: docker/Dockerfile
    cc18_server:
        build:
            args:
                - "DOCKER_USER=david"
                - "SERVER_TIME_ZONE=CET"

        environment:
            APACHE_RUN_USER: "david"
            APACHE_RUN_GROUP: "david"

        external_links:
            - "cc18_api:testapi.com"
            - "cc18_api_java:testapijava.com"

        ports:
            - "8080:80"

    # See: https://hub.docker.com/_/mysql
    cc18_mysql:
        ports:
            - "3307:3306"

    # See: https://hub.docker.com/_/rabbitmq/
    cc18_rabbitmq:
        image: "rabbitmq:3-management"

        ports:
            - "5672:5672"
            - "15672:15672"
